// <auto-generated />
using System;
using Database.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StorageManager.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250521134217_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.SQL.Models.CastomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Castomers");
                });

            modelBuilder.Entity("Database.SQL.Models.HistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CastomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CastomerId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("Database.SQL.Models.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PurchasePrice")
                        .HasColumnType("real");

                    b.Property<Guid?>("ShopEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShopEntityId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Database.SQL.Models.ShopEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Database.SQL.Models.HistoryEntity", b =>
                {
                    b.HasOne("Database.SQL.Models.CastomerEntity", "Castomer")
                        .WithMany("Histories")
                        .HasForeignKey("CastomerId");

                    b.HasOne("Database.SQL.Models.ProductEntity", "Product")
                        .WithOne("History")
                        .HasForeignKey("Database.SQL.Models.HistoryEntity", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.SQL.Models.ShopEntity", "Shop")
                        .WithMany("Histories")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Castomer");

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Database.SQL.Models.ProductEntity", b =>
                {
                    b.HasOne("Database.SQL.Models.ShopEntity", null)
                        .WithMany("Products")
                        .HasForeignKey("ShopEntityId");
                });

            modelBuilder.Entity("Database.SQL.Models.CastomerEntity", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Database.SQL.Models.ProductEntity", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Database.SQL.Models.ShopEntity", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
